// File generated by Antigravity to support multi-platform Firebase initialization.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with [Firebase.initializeApp].
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJhq-MUyezdzYLrMWY0qiuR8Q6hY-LQfY',
    appId: '1:775748763322:web:ef8c09cf7c0e887d18cc83',
    messagingSenderId: '775748763322',
    projectId: 'dropout-prediction-af891',
    authDomain: 'dropout-prediction-af891.firebaseapp.com',
    storageBucket: 'dropout-prediction-af891.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaR9u-078EYv7oGzPJBExvItsZsR8qNRA',
    appId: '1:775748763322:android:ddfcb00d6039885718cc83',
    messagingSenderId: '775748763322',
    projectId: 'dropout-prediction-af891',
    storageBucket: 'dropout-prediction-af891.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaR9u-078EYv7oGzPJBExvItsZsR8qNRA',
    appId: '1:775748763322:ios:a4dcb30f78cc83e918cc83',
    messagingSenderId: '775748763322',
    projectId: 'dropout-prediction-af891',
    storageBucket: 'dropout-prediction-af891.firebasestorage.app',
    iosBundleId: 'com.bitzapp.dropoutprediction',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJhq-MUyezdzYLrMWY0qiuR8Q6hY-LQfY',
    appId: '1:775748763322:web:ef8c09cf7c0e887d18cc83',
    messagingSenderId: '775748763322',
    projectId: 'dropout-prediction-af891',
    authDomain: 'dropout-prediction-af891.firebaseapp.com',
    storageBucket: 'dropout-prediction-af891.firebasestorage.app',
  );
}
